// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef DRIVESYSTEM_H
#define DRIVESYSTEM_H
#include "Commands/Subsystem.h"
#include "WPILib.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class DriveSystem: public Subsystem {
private:
	// It's desirable that everything possible is private except
	// for methods that implement subsystem capabilities
public:
	std::shared_ptr<SpeedController> frontLeft;
	std::shared_ptr<SpeedController> frontRight;
	std::shared_ptr<SpeedController> rearLeft;
	std::shared_ptr<SpeedController> rearRight;
	std::shared_ptr<RobotDrive> robotDrive;

	void drive(std::shared_ptr<Joystick> left, std::shared_ptr<Joystick> right);
	void stop();

	DriveSystem();
	void InitDefaultCommand();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
};

#endif
